# Generated by Django 2.1.2 on 2018-12-10 21:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Manager', '0002_auto_20181211_0322'),
        ('eat_at_canteen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='item_review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest_pub_date', models.DateTimeField(default=datetime.datetime.now)),
                ('content', models.TextField(max_length=1000)),
                ('rating', models.IntegerField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('customer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Manager.Food_items')),
            ],
        ),
    ]
