# Generated by Django 2.1.2 on 2018-12-11 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0002_admin_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='canteen_pincode',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
