# Generated by Django 2.0.2 on 2018-12-10 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paytmtxnhistory',
            name='TXNID',
            field=models.CharField(max_length=100, verbose_name='TXN ID'),
        ),
    ]
