# Generated by Django 2.1.2 on 2018-12-12 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaytmTxnHistory',
            new_name='PaytmTxnHistory0',
        ),
    ]
