# Generated by Django 2.1.2 on 2018-12-08 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='username',
            field=models.CharField(default='', max_length=200),
        ),
    ]
