# Generated by Django 2.1.2 on 2018-12-08 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
