# Generated by Django 2.1.2 on 2018-12-01 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0002_auto_20181202_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffdetails',
            name='employee_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
