# Generated by Django 2.1.2 on 2018-12-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0002_userprofileinfo_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='static/registration/profile_pics'),
        ),
    ]
