# Generated by Django 2.1.2 on 2018-12-08 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0002_auto_20181208_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='username',
        ),
    ]
