# Generated by Django 2.1.2 on 2018-12-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0003_remove_userprofileinfo_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='static/registration/profile_pics'),
        ),
    ]
