# Generated by Django 2.1.2 on 2018-12-12 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0003_auto_20181212_2211'),
        ('Registration', '0003_auto_20181212_2036'),
    ]

    operations = [
    ]
