# Generated by Django 2.1.2 on 2018-11-17 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0015_auto_20181117_1728'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Staff',
            new_name='Staffdetails',
        ),
    ]
