# Generated by Django 2.1.2 on 2018-11-17 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0016_auto_20181117_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffdetails',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
