# Generated by Django 2.1.2 on 2018-11-17 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0017_auto_20181117_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffdetails',
            name='city',
        ),
        migrations.AddField(
            model_name='staffdetails',
            name='pincode',
            field=models.CharField(default='', max_length=6),
        ),
    ]
