# Generated by Django 2.1.2 on 2018-11-17 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0019_auto_20181118_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffdetails',
            name='employee_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
