# Generated by Django 2.1.2 on 2018-11-17 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0020_auto_20181118_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffdetails',
            name='employee_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
