# Generated by Django 2.1.2 on 2018-11-17 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0021_auto_20181118_0256'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffdetails',
            name='password2',
            field=models.CharField(default='', max_length=50),
        ),
    ]
