# Generated by Django 2.1.2 on 2018-11-17 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0022_staffdetails_password2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffdetails',
            name='password2',
        ),
    ]
