# Generated by Django 2.1.2 on 2018-11-17 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0023_remove_staffdetails_password2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='id',
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='username',
            field=models.CharField(default='', max_length=25, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
    ]
