# Generated by Django 2.1.2 on 2018-11-17 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0024_auto_20181118_0408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='username',
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='Email',
            field=models.EmailField(default='', max_length=200, primary_key=True, serialize=False),
        ),
    ]
