# Generated by Django 2.1.2 on 2018-11-17 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0025_auto_20181118_0411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='Email',
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
