# Generated by Django 2.1.2 on 2018-11-16 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TokenId', models.IntegerField()),
                ('FoodId', models.IntegerField()),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.FloatField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('TableId', models.IntegerField()),
                ('Status', models.CharField(choices=[('dr', 'draft'), ('conf', 'confirmed')], default='conf', max_length=8)),
            ],
        ),
        migrations.DeleteModel(
            name='Customer_Food',
        ),
        migrations.AddField(
            model_name='order_user',
            name='status',
            field=models.CharField(choices=[('ordered', 'ordered'), ('cancelled', 'cancelled'), ('in Preparation', 'in Preparation'), ('in Delivery', 'in Delivery'), ('Completed', 'Completed')], default='ordered', max_length=12),
        ),
        migrations.AlterField(
            model_name='order_user',
            name='TokenId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='User.Order_Food'),
        ),
        migrations.AlterField(
            model_name='order_user',
            name='mailId',
            field=models.EmailField(max_length=255),
        ),
    ]
