# Generated by Django 2.1.1 on 2018-11-28 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_user',
            name='status',
            field=models.CharField(choices=[('ordered', 'ordered'), ('cancelled', 'cancelled'), ('in Preparation', 'in Preparation'), ('in Delivery', 'in Delivery'), ('draft', 'draft'), ('Completed', 'complete'), ('User Conform', 'User Conform')], default='draft', max_length=255),
        ),
    ]
