# Generated by Django 2.1.2 on 2018-11-16 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20181116_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_food',
            name='FoodId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manager.Food_items'),
        ),
    ]
