# Generated by Django 2.1.2 on 2018-11-17 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_auto_20181116_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_user',
            name='totalprice',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='order_food',
            name='Status',
            field=models.CharField(choices=[('dr', 'draft'), ('conf', 'confirmed')], default='dr', max_length=8),
        ),
        migrations.AlterField(
            model_name='order_food',
            name='TokenId',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='order_user',
            name='TokenId',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='order_user',
            name='status',
            field=models.CharField(choices=[('ordered', 'ordered'), ('cancelled', 'cancelled'), ('in Preparation', 'in Preparation'), ('in Delivery', 'in Delivery'), ('Completed', 'Completed'), ('draft', 'draft')], default='draft', max_length=12),
        ),
    ]
