# Generated by Django 2.1.2 on 2018-11-17 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_auto_20181117_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_food',
            name='date',
        ),
        migrations.RemoveField(
            model_name='order_food',
            name='time',
        ),
        migrations.AddField(
            model_name='order_user',
            name='date',
            field=models.DateField(default=''),
        ),
        migrations.AddField(
            model_name='order_user',
            name='time',
            field=models.TimeField(default=''),
        ),
    ]
