# Generated by Django 2.1.2 on 2018-11-17 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_auto_20181117_2000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_user',
            old_name='totalprice',
            new_name='totalPrice',
        ),
    ]
