# Generated by Django 2.1.2 on 2018-11-17 14:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_auto_20181117_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_user',
            name='date',
            field=models.DateField(default=datetime.date(2018, 11, 17)),
        ),
        migrations.AlterField(
            model_name='order_user',
            name='time',
            field=models.TimeField(default=datetime.time(20, 13, 57, 998391)),
        ),
    ]
