# Generated by Django 2.1.2 on 2018-11-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_auto_20181117_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_user',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='order_user',
            name='time',
            field=models.TimeField(),
        ),
    ]
