# Generated by Django 2.1.2 on 2018-11-17 17:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_auto_20181117_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_user',
            name='date',
        ),
        migrations.RemoveField(
            model_name='order_user',
            name='time',
        ),
        migrations.AddField(
            model_name='order_food',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order_food',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
