# Generated by Django 2.1.2 on 2018-11-18 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_auto_20181117_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_food',
            name='date',
        ),
        migrations.RemoveField(
            model_name='order_food',
            name='time',
        ),
    ]
