# Generated by Django 2.1.2 on 2018-12-09 12:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HD_Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('town', models.CharField(choices=[('Sri City', 'Sri City')], default='Sri City', max_length=225)),
                ('street', models.CharField(max_length=225)),
                ('dNo', models.CharField(max_length=225)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('tokenId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Order_User')),
            ],
        ),
    ]
