# Generated by Django 2.1.2 on 2018-12-10 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food_items',
            name='No_of_reviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='food_items',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
