# Generated by Django 2.1.2 on 2018-12-11 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food_items',
            name='No_of_reviews',
        ),
        migrations.RemoveField(
            model_name='food_items',
            name='rating',
        ),
    ]
