# Generated by Django 2.1.2 on 2018-12-11 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0003_auto_20181211_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='static/Manager/Admin_img/')),
            ],
        ),
    ]
