# Generated by Django 2.1.2 on 2018-12-11 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0004_admin_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_image',
            name='categories',
            field=models.CharField(choices=[('background', 'background'), ('workplace', 'workplace'), ('service', 'service')], default='service', max_length=10),
        ),
    ]
